-- 补建缺失的 3 张表

CREATE TABLE IF NOT EXISTS oa_mail_message (
  id BIGINT PRIMARY KEY,
  sender_id BIGINT NOT NULL,
  subject VARCHAR(200) NOT NULL,
  content TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS oa_mail_recipient (
  id BIGINT PRIMARY KEY,
  mail_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  recipient_type VARCHAR(10) NOT NULL COMMENT 'to/cc/bcc',
  read_status TINYINT DEFAULT 0,
  read_at DATETIME,
  email_status VARCHAR(20) DEFAULT 'pending',
  email_error VARCHAR(500),
  email_sent_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_announcement (
  id BIGINT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  content TEXT,
  category VARCHAR(50),
  target_type VARCHAR(20) DEFAULT 'all',
  target_dept_id BIGINT,
  pinned TINYINT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'draft',
  publisher_id BIGINT,
  published_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
